name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    - name: Test package
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install pytest
        pytest
    - name: Build package
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install build
        python -m build
    - name: Publish to PyPI
      # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install twine
        twine upload dist/*
